resource_group_name           = "cmtr-7ymyr7zc-mod9-rg"
location                      = "East US"
virtual_network_name          = "cmtr-7ymyr7zc-mod9-vnet"
virtual_network_address_space = "10.0.0.0/16"
aks_subnet_name               = "aks-snet"
aks_subnet_address_prefix     = "10.0.0.0/24"
aks_cluster_name              = "cmtr-7ymyr7zc-mod9-aks"
aks_loadbalancer_ip           = "20.241.178.79"
naming_prefix                 = "cmtr-7ymyr7zc-mod9"
firewall_public_ip_name       = "cmtr-7ymyr7zc-mod9-pip"
tags                          = { project = "epam-campus-mod9" }